# Postgresql | First you need to manually create a database, the plugin will create the tables itself.
pg.enabled: false
pg.host: localhost
pg.port: 5432
pg.login: postgres
pg.password: postgres
pg.dbname: coldysteps

# By what percentage to reduce the received cold and increase its disappearance for certain rights
permission.vip: 0.15
permission.premium: 0.30
permission.deluxe: 0.45

# Amount of damage per second when the player is 100% cold
damage: 2.5

# How many percent of cold is removed per second in various situations
remove.outbiome: 0.2 # Outside the cold biome (Cold biomes are specified in the biomes.yml file)
remove.fire: 5.0 # In Fire
remove.lava: 20.0 # In Lava
remove.leather: 0.02 # How much cold is removed for ONE worn leather armor
remove.food: true # Remove the cold when the player eats certain food (Specified in the food.yml file)
remove.radius: 3 # Within a radius of how many blocks around the removing block (in the blocks.yml file) the cold is removed

# How many percent of cold is added per second in various situations
add.inbiome: 1.0 # Inside the cold biome (biomes.yml)
add.water: 6.0 # In water in cold biome
add.thunder: 3.0 # In thunder in cold biome
add.leather: 0.2 # How much cold is added when ONE worn leather armor
add.effects.enable: true # Whether to add effects when the player has a certain percentage of cold (They are specified in the effects.yml file)
add.effects.cold: 90 # At what percentage of cold to add effects to the player

# Indicator settings
indicator.actionbar: true
indicator.full: "&6&l[&4##########&6&l]"
indicator.char.first: "&f#"
indicator.char.second: "&8-"
indicator.format: "&6&l[{INDICATOR}&6&l]"



# DO NOT TOUCH THIS
config.version: 1